### ISSUE TITLE
Installing pynio with anaconda

### ISSUE THREAD

**Issue by antoineribiere** [NCAR/pynio#11]
I'm trying to install pynio through anaconda.

I have a fresh environments named "pynio_env" created using  `conda create --name pynio_env --channel conda-forge pynio pyngl` .

 When importing with `import pynio` I get the following error message : `ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory`. 

Can I know how to solve this problem?

**Comment by khallock** [comment]
Hi @antoineribiere,

There is a known issue that prevents installation of both PyNIO and PyNGL from conda-forge at the moment. If you don't need PyNGL, please try running `conda create --name pynio_env --channel conda-forge pynio` (without pyngl) and let me know if you are still having issues importing pynio.

**Comment by antoineribiere** [comment]
Thanks a lot! This solved my issue.

**Comment by khallock** [comment]
Great! Thanks for letting us know that worked!
