### ISSUE TITLE
conda installation not working on Mac OS

### ISSUE THREAD

**Issue by gioper86** [NCAR/pynio#3]
I have tried installing PyNIO through anaconda. Installation goes fine but when I import the library in my script I get the following error (I have tried both version 1.4.3 and 1.5.0):

  File "myscript.py", line 1, in <module>
    import Nio
  File "/Users/Romonet/anaconda/lib/python2.7/site-packages/PyNIO/Nio.py", line 63, in <module>
    from nio import *
ImportError: dlopen(/Users/Romonet/anaconda/lib/python2.7/site-packages/PyNIO/nio.so, 2): Library not loaded: @rpath/./libhdf5_cpp.10.dylib
  Referenced from: /Users/Romonet/anaconda/lib//libkea.1.4.5.dylib
  Reason: image not found

I then tried creating a symbolic link to libhdf5_cpp.10.dylib in /usr/lib but when I do that I get a different error.

**Comment by david-ian-brown** [comment]
I experienced this same error and was able to eliminate it by doing:

conda update kealib

I am not sure why the dependency checking did not find this and
automatically update it when the new version of the hdf5 library was
installed. The current version of libgdal has a dependency on libkea.

Let me know if this doesn't work.

**Comment by gioper86** [comment]
That worked, thanks!
